Importar PyTorch: Comienza importando Torch, la esencia de PyTorch. Esto es crucial ya que permite operar con tensores de manera eficiente.

In [34]:
import torch
print(torch.__version__)

2.8.0


Tensores básicos: Los tensores pueden tomar la forma de escalares, vectores, o matrices:

Escalar: Un tensor de un solo valor, por ejemplo, el número tres.

In [35]:
scalar = torch.tensor(3.0)
scalar

tensor(3.)

Vector: Una secuencia de escalares, o números, por ejemplo, [1, 2, 3].

In [36]:
vector = torch.tensor([1.0, 2.0, 3.0])
vector

tensor([1., 2., 3.])

Matriz: Una organización más compleja que implica vectores apilados, formada por filas y columnas.

In [37]:
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

Tensor de 3 dimensiones: Cuando una estructura supera las dos dimensiones, es donde realmente brillan los tensores, permitiendo representaciones más complejas.

In [38]:
tensor_3d = torch.randn(5, 2, 3)
print(tensor_3d)

tensor([[[-0.4866, -0.3787,  0.9910],
         [ 1.5809, -0.8709, -1.0653]],

        [[ 0.0246, -0.6720, -1.4274],
         [ 0.6417,  1.2918, -0.4068]],

        [[-1.0701,  1.0414,  0.6171],
         [-0.0145,  0.3659, -0.9623]],

        [[ 0.1666,  0.9423, -0.0562],
         [-1.2283,  0.2523, -0.1891]],

        [[-0.1309, -1.0370, -2.9628],
         [ 0.5211, -1.0436,  1.0707]]])


In [39]:
escalar = torch.randn(1)
vector = torch.zeros(1, 10)
matriz = torch.ones(2,2)

matriz

tensor([[1., 1.],
        [1., 1.]])

In [40]:
t5 = torch.randn(5,2,3)
t5

tensor([[[-1.2701e-01, -1.8707e+00, -6.9064e-01],
         [-1.1765e+00,  1.4161e+00, -7.8410e-01]],

        [[ 1.3651e-03,  3.8355e-01, -7.3558e-01],
         [ 4.0910e-01,  5.4377e-02,  8.6232e-01]],

        [[ 1.8869e-01,  2.1136e-01,  1.6717e+00],
         [-1.7081e+00, -1.5601e+00, -1.1933e+00]],

        [[ 3.6411e-01, -6.2777e-01, -7.8444e-01],
         [-3.9916e-01,  1.2654e+00, -1.6606e-01]],

        [[ 3.8586e-01,  1.6242e+00, -1.1318e+00],
         [-4.7210e-01,  4.0633e-01, -6.4811e-01]]])

In [41]:
torch.tensor([[2,2], [3,3]])

tensor([[2, 2],
        [3, 3]])

In [42]:
# Obtener la forma de una matriz
print(f"la forma de la matriz es {matriz.shape}")

# Obtener la forma de un tensor t5
print(f"la forma de t5 es {t5.shape}")

la forma de la matriz es torch.Size([2, 2])
la forma de t5 es torch.Size([5, 2, 3])


In [43]:
# Obtener las dimensiones de una matriz
print(f"la forma de la matriz es {matriz.ndim}")

# Obtener las dimensiones de un tensor t5
print(f"la forma de t5 es {t5.ndim}")

la forma de la matriz es 2
la forma de t5 es 3


In [44]:
# Obtener el tipo de objeto de una matriz
print(f"la forma de la matriz es {matriz.dtype}")

# Obtener el tipo de objeto de un tensor t5
print(f"la forma de t5 es {t5.dtype}")

la forma de la matriz es torch.float32
la forma de t5 es torch.float32


In [45]:
matriz_float32 = torch.tensor([[3.1,3.2],[3.3,3.4]])
matriz_unit64 = torch.tensor([[3,3],[3,3]])


matriz_float32.dtype, matriz_unit64.dtype

(matriz_float32 + matriz_unit64)

tensor([[6.1000, 6.2000],
        [6.3000, 6.4000]])

cambiar de enteros a float32 con to

In [46]:
matriz_unit64.to(torch.float32)

tensor([[3., 3.],
        [3., 3.]])

In [47]:
matriz_unit64.device

device(type='cpu')

In [53]:

print(torch.backends.mps.is_available())

True


In [54]:

if torch.backends.mps.is_available():
    device = torch.device("mps")
    print("Usando GPU de Apple (MPS) 🍏")
else:
    device = torch.device("cpu")
    print("Usando CPU 🧠")

Usando GPU de Apple (MPS) 🍏
