In [1]:
import numpy as np
import torch

# Creación de un vector de NumPy con unos
vector = np.ones(4, dtype=np.float32)

# Conversión de NumPy a PyTorch
tensor = torch.from_numpy(vector)

In [2]:
# Conversión de PyTorch a NumPy
array = tensor.numpy()

In [7]:
vector = np.ones(5)
torch.from_numpy(vector).dtype

torch.float64

In [3]:
# Definición de tensores
zeros_tensor = torch.zeros((3, 4))
ones_tensor = torch.ones((3, 4))

# Suma de tensores
sum_tensor = zeros_tensor + ones_tensor

# Multiplicación elemento por elemento
mul_tensor = zeros_tensor * ones_tensor


In [8]:
zeros_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
sum_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [11]:
mul_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [4]:
random_tensor = torch.rand(4)

# Podemos dividirlo por el tensor de unos
div_tensor = random_tensor / ones_tensor

In [12]:
div_tensor

tensor([[0.6992, 0.7485, 0.0925, 0.0884],
        [0.6992, 0.7485, 0.0925, 0.0884],
        [0.6992, 0.7485, 0.0925, 0.0884]])

In [13]:
matrix1 = torch.rand((2, 3))
matrix2 = torch.rand((3, 2))

# Multiplicación de matrices
result_tensor = torch.matmul(matrix1, matrix2)
result_tensor

tensor([[0.8912, 0.4203],
        [1.6787, 0.8865]])